// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Step 1
---
*/
package cmds

import (
	"context"

	"github.com/365admin/koksmat-hooks/execution"
)

func TasksStep1Post(ctx context.Context, args []string) (*string, error) {

	_, pwsherr := execution.ExecutePowerShell("john", "*", "koksmat-hooks", "20-tasks", "10-receiver.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	return nil, nil

}
