// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Step 1
---
*/
package endpoints

import (
	"context"

	"github.com/365admin/koksmat-hooks/execution"
	"github.com/swaggest/usecase"
)

func TasksStep1Post() usecase.Interactor {
	type Request struct {
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "koksmat-hooks", "20-tasks", "10-receiver.ps1", "")
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Step 1")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Tasks")
	return u
}
